server:
  port: 8090

spring:
  application:
    name: admin-server

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.112:8761/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: health
