spring:
  application:
    name: order
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
  config:
    import: configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health
