spring:
  application:
    name: product
  config:
    import: configserver:http://host.docker.internal:8888

  boot:
    admin:
      client:
        url: http://host.docker.internal:8090
        instance:
          prefer-ip: true
          service-url: http://192.168.1.112:8082

eureka:
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 192.168.1.112
    instance-id: product:8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
