server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/KabiraEttalbi/microservices-configuration.git
          default-label: main
          search-paths: '{application}'

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true
    
management:
  endpoints:
    web:
      exposure:
        include: health



